defmodule Canary.Repo.Migrations.InitAsh do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:source_websites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :base_url, :text, null: false
    end

    create table(:source_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_id, :uuid, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:source_documents, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :content, :text
      add :embedding, :vector

      add :snapshot_id,
          references(:source_snapshots,
            column: :id,
            name: "source_documents_snapshot_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:client_websites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_id, :uuid, null: false
      add :base_url, :text, null: false
      add :public_key, :text, null: false, default: fragment("gen_random_uuid()")
    end

    create table(:accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:source_websites) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "source_websites_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:client_websites) do
      modify :account_id,
             references(:accounts,
               column: :id,
               name: "client_websites_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:accounts) do
      add :user_id, :uuid, null: false
      add :name, :text, null: false
    end

    create table(:account_users, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "account_users_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "account_users_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:account_users, "account_users_user_id_fkey")

    drop constraint(:account_users, "account_users_account_id_fkey")

    drop table(:account_users)

    alter table(:accounts) do
      remove :name
      remove :user_id
    end

    drop constraint(:client_websites, "client_websites_account_id_fkey")

    alter table(:client_websites) do
      modify :account_id, :uuid
    end

    drop constraint(:source_websites, "source_websites_account_id_fkey")

    alter table(:source_websites) do
      modify :account_id, :uuid
    end

    drop table(:accounts)

    drop table(:client_websites)

    drop constraint(:source_documents, "source_documents_snapshot_id_fkey")

    drop table(:source_documents)

    drop table(:source_snapshots)

    drop table(:source_websites)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
