defmodule Canary.Repo.Migrations.AddMembershipOverride do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:billings) do
      add :membership_override_tier, :text
      add :membership_override_ends_at, :utc_datetime
    end
  end

  def down do
    alter table(:billings) do
      remove :membership_override_ends_at
      remove :membership_override_tier
    end
  end
end
