defmodule Canary.Repo.Migrations.AddInsightsConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:insights_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :aliases, {:array, :map}, default: []

      add :project_id,
          references(:projects,
            column: :id,
            name: "insights_configs_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:insights_configs, "insights_configs_project_id_fkey")

    drop table(:insights_configs)
  end
end
