defmodule Canary.Repo.Migrations.MultiAccountsSupport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts) do
      add :name, :text
      add :selected, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:accounts) do
      remove :selected
      remove :name
    end
  end
end
