defmodule Canary.Repo.Migrations.AddMissingNonNull do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :account_id, :uuid, null: false
    end

    alter table(:github_apps) do
      modify :account_id, :uuid, null: false
    end

    alter table(:documents) do
      modify :source_id, :uuid, null: false
      modify :index_id, :uuid, null: false
    end

    alter table(:billings) do
      modify :account_id, :uuid, null: false
    end
  end

  def down do
    alter table(:billings) do
      modify :account_id, :uuid, null: true
    end

    alter table(:documents) do
      modify :index_id, :uuid, null: true
      modify :source_id, :uuid, null: true
    end

    alter table(:github_apps) do
      modify :account_id, :uuid, null: true
    end

    alter table(:users) do
      modify :account_id, :uuid, null: true
    end
  end
end
