defmodule Canary.Repo.Migrations.AddDiscordChannelId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clients) do
      add :discord_channel_id, :bigint
    end

    create unique_index(:clients, [:discord_server_id, :discord_channel_id],
             name: "clients_unique_discord_index"
           )

    create unique_index(:clients, [:web_base_url, :web_public_key],
             name: "clients_unique_web_index"
           )
  end

  def down do
    drop_if_exists unique_index(:clients, [:web_base_url, :web_public_key],
                     name: "clients_unique_web_index"
                   )

    drop_if_exists unique_index(:clients, [:discord_server_id, :discord_channel_id],
                     name: "clients_unique_discord_index"
                   )

    alter table(:clients) do
      remove :discord_channel_id
    end
  end
end
