defmodule Canary.Repo.Migrations.MemberInviteWithoutUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:account_invites) do
      remove :user_id
    end
  end

  def down do
    alter table(:account_invites) do
      add :user_id,
          references(:users,
            column: :id,
            name: "account_invites_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
