defmodule Canary.Repo.Migrations.AddCascadeDeleteForClientSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:client_sources, "client_sources_source_id_fkey")

    drop constraint(:client_sources, "client_sources_client_id_fkey")

    alter table(:client_sources) do
      modify :client_id,
             references(:clients,
               column: :id,
               name: "client_sources_client_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute(
      "ALTER TABLE client_sources alter CONSTRAINT client_sources_client_id_fkey NOT DEFERRABLE"
    )

    alter table(:client_sources) do
      modify :source_id,
             references(:sources,
               column: :id,
               name: "client_sources_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute(
      "ALTER TABLE client_sources alter CONSTRAINT client_sources_source_id_fkey NOT DEFERRABLE"
    )
  end

  def down do
    drop constraint(:client_sources, "client_sources_source_id_fkey")

    alter table(:client_sources) do
      modify :source_id,
             references(:sources,
               column: :id,
               name: "client_sources_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:client_sources, "client_sources_client_id_fkey")

    alter table(:client_sources) do
      modify :client_id,
             references(:clients,
               column: :id,
               name: "client_sources_client_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
