defmodule Canary.Repo.Migrations.AddDiscordClient do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sources) do
      remove :last_fetched_at
    end

    alter table(:source_documents) do
      modify :content_hash, :binary, null: false
      modify :content, :text, null: false
    end

    alter table(:clients) do
      modify :web_public_key, :text, default: nil
      add :discord_server_id, :bigint
    end
  end

  def down do
    alter table(:clients) do
      remove :discord_server_id
      modify :web_public_key, :text, default: fragment("gen_random_uuid()")
    end

    alter table(:source_documents) do
      modify :content, :text, null: true
      modify :content_hash, :binary, null: true
    end

    alter table(:sources) do
      add :last_fetched_at, :utc_datetime_usec
    end
  end
end
