defmodule Canary.Repo.Migrations.AddClientName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clients) do
      add :name, :text, null: false
    end
  end

  def down do
    alter table(:clients) do
      remove :name
    end
  end
end
