defmodule Canary.Repo.Migrations.AddUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:usages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :generation, :bigint, default: 0

      add :account_id,
          references(:accounts,
            column: :id,
            name: "usages_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:usages, "usages_account_id_fkey")

    drop table(:usages)
  end
end
