defmodule Canary.Repo.Migrations.FixUserAccountRelation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts) do
      remove :user_id
    end
  end

  def down do
    alter table(:accounts) do
      add :user_id, :uuid, null: false
    end
  end
end
