defmodule Canary.Repo.Migrations.AddParentIndexIdInDocument do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:documents) do
      add :parent_index_id, :text
    end
  end

  def down do
    alter table(:documents) do
      remove :parent_index_id
    end
  end
end
