/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AskResponse {
  scratchpad?: string;
  blocks: (AskResponseTextBlock | AskResponseReferenceBlock)[];
}
export interface AskResponseTextBlock {
  type: "text";
  text: string;
}
export interface AskResponseReferenceBlock {
  type: "reference";
  title: string;
  url: string;
  sections: {
    title?: string;
    url?: string;
    excerpt: string;
    explanation: string;
  }[];
}
