version: "3"
dotenv:
  - .env
tasks:
  dev:
    cmds:
      - docker-compose up -d
      - sleep 3
      - mix ecto.migrate
      - iex --sname canary --cookie canary -S mix phx.server
      - docker-compose down
