version: "3"
dotenv:
  - .env
tasks:
  dev:
    cmds:
      - docker-compose up -d
      - sleep 2
      - mix ecto.migrate
      - task: trieve:create
      - task: phx:start
      - docker-compose down
      - task: trieve:delete
  phx:start:
    cmds:
      - |
        TRIEVE_DATASET=$(cat /tmp/trieve_dataset) &&
        iex --sname canary --cookie canary -S mix phx.server
  trieve:create:
    cmds:
      - |
        TRIEVE_DATASET=$(curl --request POST \
          --url https://api.trieve.ai/api/dataset \
          --header "Authorization: Bearer ${TRIEVE_API_KEY}" \
          --header "Content-Type: application/json" \
          --header "TR-Organization: ${TRIEVE_ORGANIZATION}" \
          --data "{\"dataset_name\":\"__DEV__\"}" | jq -r '.id')
        echo $TRIEVE_DATASET > /tmp/trieve_dataset
  trieve:delete:
    cmds:
      - |
        TRIEVE_DATASET=$(cat /tmp/trieve_dataset)
        curl --request DELETE \
          --url https://api.trieve.ai/api/dataset/${TRIEVE_DATASET} \
          --header "TR-Organization: ${TRIEVE_ORGANIZATION}" \
          --header "Authorization: Bearer ${TRIEVE_API_KEY}" \
          --header "TR-Dataset: ${TRIEVE_DATASET}" || true
