# https://github.com/neondatabase/preview-branches-with-fly
on:
  pull_request:
    types: [closed]
env:
  NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/fly-pr-review-apps@1.2.0
      - uses: neondatabase/delete-branch-action@v3.1.3
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          branch: preview/${{ github.event.pull_request.head.ref }}
          api_key: ${{ secrets.NEON_API_KEY }}
